kind: Service
apiVersion: v1
metadata:
  name: pieces-finder-service
  namespace: speculaas
spec:
  type: NodePort
  selector:
    app: pieces-finder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
