[package]
name = "opencv-wasm-spike"
version = "0.2.0"
authors = ["Mike Moran <mike@houseofmoran.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.50"
opencv = {version = "0.20.0", default-features = false, features = ["opencv-41"]}
