kind: Service
apiVersion: v1
metadata:
  name: pieces-view-service
  namespace: speculaas
  annotations:
    external-dns.alpha.kubernetes.io/hostname: speculaas.houseofmoran.io.
spec:
  type: LoadBalancer
  selector:
    app: pieces-view
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
