kind: Service
apiVersion: v1
metadata:
  name: pieces-view-service
  namespace: speculaas
spec:
  type: NodePort
  selector:
    app: pieces-view
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
